repos:
  - hooks:
      - args:
          - --remove-all-unused-imports
          - --in-place
        id: autoflake
    repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
  - hooks:
      - args:
          - --profile=black
          - --line-length=120
        id: isort
    repo: https://github.com/pycqa/isort
    rev: 5.12.0
  - hooks:
      - args:
          - --line-length=120
        id: black
    repo: https://github.com/psf/black
    rev: 23.3.0
  - hooks:
      - id: ruff
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.0
